apiVersion: apps/v1
kind: Deployment
metadata:
  name: discordweb
spec:
  replicas: 1
  selector:
    matchLabels:
      type: discordweb
      service: discordweb
      color: green
  minReadySeconds: 1
  progressDeadlineSeconds: 60
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        type: discordweb
        service: discordweb
        color: green
        language: javascript
    spec:
      imagePullSecrets:
      - name: repo
      containers:
      - name: discordweb
        image: #{web_image}#
        ports:
        - containerPort: 8080
          name: discordweb
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          periodSeconds: 1
        livenessProbe:
          httpGet:
            path: /
            port: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: discordweb
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    type: discordweb
    service: discordweb
    color: green

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: discordapi
spec:
  replicas: 1
  selector:
    matchLabels:
      type: discordapi
      service: discordapi
      color: blue
  minReadySeconds: 1
  progressDeadlineSeconds: 60
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        type: discordapi
        service: discordapi
        color: blue
        language: javascript
    spec:
      imagePullSecrets:
      - name: repo
      containers:
      - name: discordapi
        image: #{api_image}#
        ports:
        - containerPort: 3000
          name: discordapi

---

apiVersion: v1
kind: Service
metadata:
  name: discordapi
spec:
  type: LoadBalancer
  ports:
  - port: 3000
  selector:
    type: discordapi
    service: discordapi
    color: blue