trigger:
  - master

queue:
  name: Default

steps:
- powershell: |
   terraform init
   terraform plan -out="terraform.tfplan" -var "do_token=$(doToken)"
  workingDirectory: src/digitalocean
  displayName: 'PowerShell Script'

- task: CopyFiles@2
  displayName: 'Copy Digitalocean Deployment configs to: $(Build.ArtifactStagingDirectory)'
  inputs:
    SourceFolder: ./src/digitalocean
    Contents: |
     **/*

    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: do-plan'
  inputs:
    ArtifactName: 'do-plan'
